"use client";

import { useEffect, useRef } from "react";
import type { CommunityCitySummary } from "../../features/map/community-map";
import type { AmapDistrict, AmapMap, AmapNamespace, AmapOverlay } from "./AmapLoader";

function escapeHtml(value: string): string { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character); }
function loadDistrict(amap: AmapNamespace, city: string): Promise<AmapDistrict | undefined> { return new Promise((resolve) => { const search = new amap.DistrictSearch({ level: "city", subdistrict: 0, extensions: "all" }); search.search(`${city}市`, (status, result) => resolve(status === "complete" && typeof result !== "string" ? result.districtList?.[0] : undefined)); }); }
function districtPolygons(amap: AmapNamespace, district: AmapDistrict | undefined, active: boolean): AmapOverlay[] { return district?.boundaries?.map((path) => new amap.Polygon({ path, strokeColor: active ? "#f07832" : "#4776bd", strokeWeight: active ? 3 : 1.5, strokeOpacity: .9, fillColor: active ? "#ffe2a6" : "#d9e9ff", fillOpacity: active ? .62 : .32, bubble: true })) ?? []; }

export function CommunityMapCanvas({ amap, cities, activeCity, onSelectCity, onFailure }: { amap: AmapNamespace; cities: CommunityCitySummary[]; activeCity?: string; onSelectCity: (city: string) => void; onFailure: () => void; }) {
  const containerRef = useRef<HTMLDivElement>(null); const mapRef = useRef<AmapMap>(); const overlaysRef = useRef<AmapOverlay[]>([]);
  useEffect(() => { if (!containerRef.current) return; try { const map = new amap.Map(containerRef.current, { center: [113.2665, 23.1322], zoom: 6.6, viewMode: "2D", showLabel: false, features: ["bg"], mapStyle: "amap://styles/whitesmoke" }); mapRef.current = map; return () => { map.destroy(); mapRef.current = undefined; }; } catch { onFailure(); } }, [amap, onFailure]);
  useEffect(() => { const map = mapRef.current; if (!map) return; let current = true; if (overlaysRef.current.length) map.remove(overlaysRef.current); overlaysRef.current = []; void Promise.all(cities.map(async (city) => ({ city, district: await loadDistrict(amap, city.city) }))).then((districts) => { if (!current) return; const overlays: AmapOverlay[] = []; for (const { city, district } of districts) { overlays.push(...districtPolygons(amap, district, city.city === activeCity)); const marker = new amap.Marker({ position: [city.center.lng, city.center.lat], anchor: "bottom-center", title: `${city.city}，${city.communityCount} 个社群`, content: `<button type="button" class="community-city-marker${city.city === activeCity ? " is-active" : ""}"><strong>${escapeHtml(city.city)}</strong><span>${city.communityCount} 个社群</span></button>` }); marker.on("click", () => onSelectCity(city.city)); overlays.push(marker); } overlaysRef.current = overlays; if (overlays.length) map.add(overlays); }).catch(onFailure); return () => { current = false; }; }, [activeCity, amap, cities, onFailure, onSelectCity]);
  return <div className="community-map-shell"><div ref={containerRef} className="amap-canvas" aria-label="AI 社群城市聚合地图" /><div className="map-live-label community-map-live-label"><span>AI</span><strong>城市社群</strong><small>仅展示主要活跃城市，点击查看社群</small></div></div>;
}
