"use client";

import { useState } from "react";
import { ROLE_OPTIONS, SKILL_OPTIONS } from "../../features/applications/validation";
import { AmapLoader, AmapLocationPreview, type AmapLocation, type AmapNamespace } from "../map/AmapLoader";

type School = { id: string; name: string; campus: string; city: string; coordinateStatus: string };
type Candidate = AmapLocation;
function split(value: FormDataEntryValue | null): string[] { return typeof value === "string" && value.trim() ? value.split(/[,，\n]/).map((item) => item.trim()).filter(Boolean) : []; }
function selected(form: FormData, name: string): string[] { return form.getAll(name).filter((value): value is string => typeof value === "string"); }
function coordinate(value: unknown): { longitude: number; latitude: number } | null { if (!value || typeof value !== "object") return null; const item = value as { lng?: unknown; lat?: unknown; getLng?: () => unknown; getLat?: () => unknown }; const longitude = Number(typeof item.getLng === "function" ? item.getLng() : item.lng); const latitude = Number(typeof item.getLat === "function" ? item.getLat() : item.lat); return Number.isFinite(longitude) && Number.isFinite(latitude) ? { longitude: Math.round(longitude * 1_000_000), latitude: Math.round(latitude * 1_000_000) } : null; }

function SchoolSearch({ amap, onAdded }: { amap: AmapNamespace; onAdded: (school: School) => void }) {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Candidate[]>([]); const [preview, setPreview] = useState<Candidate>(); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  function search() { const keyword = query.trim(); if (!keyword) return; setMessage("正在搜索高德地图…"); setPreview(undefined); new amap.PlaceSearch({ city: "广东" }).search(keyword, (status, value) => { const pois = status === "complete" && value && typeof value === "object" ? ((value as { poiList?: { pois?: unknown[] } }).poiList?.pois ?? []) : []; const next = pois.flatMap((poi) => { if (!poi || typeof poi !== "object") return []; const item = poi as { name?: unknown; cityname?: unknown; adname?: unknown; address?: unknown; location?: unknown }; const point = coordinate(item.location); return point && typeof item.name === "string" ? [{ name: item.name, city: typeof item.cityname === "string" && item.cityname ? item.cityname : "广州", district: typeof item.adname === "string" ? item.adname : "", address: typeof item.address === "string" ? item.address : "", ...point }] : []; }).slice(0, 8); setResults(next); setMessage(next.length ? "请选择学校地点" : "未找到地点，可前往学校坐标页手动补录。"); }); }
  async function choose(candidate: Candidate) { const campus = window.prompt("校区名称（可修改）", candidate.name) ?? ""; if (campus.trim().length < 2) return; setPending(true); try { const response = await fetch("/api/admin/schools", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "select_amap", name: candidate.name, campus: campus.trim(), city: candidate.city, longitude: candidate.longitude, latitude: candidate.latitude }) }); const school = await response.json() as School & { error?: string }; if (!response.ok) throw new Error(school.error ?? "学校保存失败"); onAdded(school); setResults([]); setPreview(undefined); setMessage(`已添加并选中 ${school.name}。`); } catch (error) { setMessage(error instanceof Error ? error.message : "学校保存失败"); } finally { setPending(false); } }
  return <section className="manual-school-search"><h2>搜索高德学校</h2><p>先查看地点和周边地图，确认后会直接加入并选中。</p><div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="例如：中山大学广州校区" aria-label="搜索高德学校" /><button type="button" className="action-primary" disabled={pending} onClick={search}>搜索</button></div>{message ? <p role="status">{message}</p> : null}{preview ? <AmapLocationPreview amap={amap} location={preview} pending={pending} onBack={() => setPreview(undefined)} onConfirm={() => void choose(preview)} /> : <ul>{results.map((candidate) => <li key={`${candidate.name}-${candidate.longitude}`}><button type="button" disabled={pending} onClick={() => setPreview(candidate)}><strong>{candidate.name}</strong><span>{[candidate.city, candidate.district, candidate.address].filter(Boolean).join(" · ")}</span></button></li>)}</ul>}</section>;
}

export function ManualMemberForm({ schools, amapKey }: { schools: School[]; amapKey?: string }) {
  const [schoolOptions, setSchoolOptions] = useState(schools); const [selectedSchoolId, setSelectedSchoolId] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  function addSchool(school: School) { setSchoolOptions((current) => current.some((item) => item.id === school.id) ? current : [...current, school]); setSelectedSchoolId(school.id); }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); const skills = selected(form, "skills"); const roles = selected(form, "roles"); if (!skills.length || !roles.length) { setMessage("请至少选择一项技能和一个参与角色"); setPending(false); return; } const body = { nickname: form.get("nickname"), realName: form.get("realName") || undefined, schoolId: form.get("schoolId"), intro: form.get("intro"), skills, interests: split(form.get("interests")), roles, workLinks: split(form.get("workLinks")), major: form.get("major") || undefined, grade: form.get("grade") || undefined, currentFocus: form.get("currentFocus") || undefined, canOffer: form.get("canOffer") || undefined, wantsToMeet: form.get("wantsToMeet") || undefined, publication: form.get("publication") }; try { const response = await fetch("/api/admin/members/manual", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { slug?: string; error?: string }; if (!response.ok) throw new Error(result.error ?? "保存失败"); setMessage(`已保存。成员资料地址：/members/${result.slug}`); event.currentTarget.reset(); setSelectedSchoolId(""); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } finally { setPending(false); } }
  return <form className="manual-member-form" onSubmit={submit}><header><p className="admin-kicker">MANUAL ENTRY</p><h1>手动录入成员</h1><p>此资料不创建登录账户，也不收集邮箱、联系方式或实时位置。默认保存为未公开草稿。</p></header><AmapLoader apiKey={amapKey}>{(state, amap) => state === "ready" && amap ? <SchoolSearch amap={amap} onAdded={addSchool} /> : <section className="manual-school-search"><h2>搜索高德学校</h2><p>{state === "failed" ? "高德搜索暂不可用，可前往学校坐标页手动补录。" : "正在加载高德搜索…"}</p></section>}</AmapLoader><section className="manual-member-grid"><label>展示昵称<input name="nickname" required minLength={2} maxLength={30} /></label><label>真实姓名（可选，不公开）<input name="realName" maxLength={60} /></label><label>学校 / 校区<select name="schoolId" required value={selectedSchoolId} onChange={(event) => setSelectedSchoolId(event.target.value)}><option value="" disabled>请选择或搜索学校</option>{schoolOptions.map((school) => <option key={school.id} value={school.id}>{school.name} · {school.campus}</option>)}</select></label><label>专业（可选）<input name="major" maxLength={100} /></label><label>年级（可选）<input name="grade" maxLength={40} /></label><label>一句话介绍<textarea name="intro" required minLength={10} maxLength={160} /></label><fieldset className="manual-choice-field"><legend>技能（至少选择一项）</legend><div>{SKILL_OPTIONS.map((skill) => <label key={skill}><input type="checkbox" name="skills" value={skill} />{skill}</label>)}</div></fieldset><label>兴趣（用逗号分隔）<input name="interests" required placeholder="校园共建" /></label><fieldset className="manual-choice-field"><legend>参与角色（至少选择一个）</legend><div>{ROLE_OPTIONS.map((role) => <label key={role}><input type="checkbox" name="roles" value={role} />{role}</label>)}</div></fieldset><label>作品链接（可选，仅 HTTPS）<input name="workLinks" placeholder="https://..." /></label><label>当前关注（可选）<textarea name="currentFocus" /></label><label>可以提供（可选）<textarea name="canOffer" /></label><label>希望认识（可选）<textarea name="wantsToMeet" /></label></section><fieldset className="manual-publication"><legend>保存方式</legend><label><input type="radio" name="publication" value="draft" defaultChecked /> 保存为草稿（不上地图）</label><label><input type="radio" name="publication" value="publish" /> 确认发布到地图</label></fieldset><button className="action-primary" type="submit" disabled={pending}>{pending ? "正在保存…" : "保存成员资料"}</button>{message ? <p className="admin-action-message" role="status">{message}</p> : null}</form>;
}
