import { BlockButton } from "../safety/BlockButton";
import { ReportDialog } from "../safety/ReportDialog";

export type ConnectionView = {
  request: { id: string; topic: string; message: string; status: string; createdAt: number; updatedAt: number; resolvedAt?: number };
  counterpartSlug?: string;
  counterpart?: { slug: string; nickname: string; avatarUrl?: string; school: string; city: string; intro: string; skills: string[] };
  unlockedContactCard?: { wechat?: string; email?: string; otherLabel?: string; otherValue?: string };
};

export function ConnectionCard({ item, box, busy, onAction, onView }: { item: ConnectionView; box: "received" | "sent" | "accepted"; busy?: boolean; onAction(action: "accept" | "decline" | "withdraw"): void; onView?(): void }) {
  const date = new Date(item.request.createdAt).toLocaleDateString("zh-CN", { month: "long", day: "numeric" });
  if (box !== "accepted" && item.counterpart) return <article className="connection-card connection-new-friend"><div className="connection-friend-avatar">{item.counterpart.avatarUrl ? <img src={item.counterpart.avatarUrl} alt="" /> : Array.from(item.counterpart.nickname)[0]}</div><div className="connection-friend-copy"><h2>{item.counterpart.nickname}</h2><p>{box === "sent" ? "我：" : ""}{item.request.message}</p></div>{box === "sent" ? <span className="connection-outgoing-status" aria-label="我发出的申请">↗ 等待验证</span> : item.request.status === "pending" ? <button className="connection-view-request" type="button" disabled={busy} onClick={onView}>查看</button> : <button className="connection-view-request" type="button" disabled>{item.request.status === "accepted" ? "已同意" : item.request.status === "declined" ? "已拒绝" : "已撤回"}</button>}</article>;
  if (box === "accepted" && item.counterpart) return <article className="connection-card connection-friend-card"><header><div className="connection-friend-identity"><div className="connection-friend-avatar">{item.counterpart.avatarUrl ? <img src={item.counterpart.avatarUrl} alt="" /> : Array.from(item.counterpart.nickname)[0]}</div><div><h2>{item.counterpart.nickname}</h2><p>{item.counterpart.school} · {item.counterpart.city}</p></div></div><a href={`/members/${item.counterpart.slug}`}>查看资料</a></header><p>{item.counterpart.intro}</p><section className="connection-contact-card" aria-label="已授权的当前联系方式"><h3>联系方式</h3>{item.unlockedContactCard ? <dl>{item.unlockedContactCard.wechat ? <><dt>微信</dt><dd>{item.unlockedContactCard.wechat}</dd></> : null}{item.unlockedContactCard.email ? <><dt>邮箱</dt><dd>{item.unlockedContactCard.email}</dd></> : null}{item.unlockedContactCard.otherValue ? <><dt>{item.unlockedContactCard.otherLabel ?? "其他"}</dt><dd>{item.unlockedContactCard.otherValue}</dd></> : null}</dl> : <p>对方暂未设置可交换的联系方式。</p>}</section>{item.counterpartSlug ? <details className="connection-safety-menu"><summary>更多安全操作</summary><BlockButton memberSlug={item.counterpartSlug} /><ReportDialog targetMemberSlug={item.counterpartSlug} requestId={item.request.id} /></details> : null}</article>;
  return <article className="connection-card"><header><div><p className="section-kicker">{box === "received" ? "收到的请求" : box === "sent" ? "发出的请求" : "已连接"}</p><h2>{item.request.topic}</h2></div><time dateTime={new Date(item.request.createdAt).toISOString()}>{date}</time></header><p className="connection-message">{item.request.message}</p>
    {box === "received" && item.request.status === "pending" ? <div className="connection-card-actions"><button type="button" disabled={busy} onClick={() => onAction("decline")}>婉拒</button><button type="button" disabled={busy} onClick={() => onAction("accept")}>接受连接</button></div> : null}
    {box === "sent" && item.request.status === "pending" ? <div className="connection-card-actions"><button type="button" disabled={busy} onClick={() => onAction("withdraw")}>撤回请求</button></div> : null}
    {box === "accepted" ? <section className="connection-contact-card" aria-label="已授权的当前联系方式"><h3>对方当前联系方式</h3>{item.unlockedContactCard ? <dl>{item.unlockedContactCard.wechat ? <><dt>微信</dt><dd>{item.unlockedContactCard.wechat}</dd></> : null}{item.unlockedContactCard.email ? <><dt>邮箱</dt><dd>{item.unlockedContactCard.email}</dd></> : null}{item.unlockedContactCard.otherValue ? <><dt>{item.unlockedContactCard.otherLabel ?? "其他"}</dt><dd>{item.unlockedContactCard.otherValue}</dd></> : null}</dl> : <p>对方暂未设置可交换的联系方式。</p>}</section> : null}
    {item.counterpartSlug ? <details className="connection-safety-menu"><summary>更多安全操作</summary><BlockButton memberSlug={item.counterpartSlug} /><ReportDialog targetMemberSlug={item.counterpartSlug} requestId={item.request.id} /></details> : null}
  </article>;
}
